### ISSUE TITLE
Selecting Monkey Dude in debug mode in Encore Angel Island breaks differently than in the original

### ISSUE THREAD

**Issue by PatchMixolydic** [Rubberduckycooly/Sonic-Mania-Decompilation#101]
The latest Steam build of Sonic Mania has a minor glitch in Encore Angel Island: selecting Monkey Dude in debug mode removes Sonic's ability to drop dash and gives you a hyper ring powerup. This doesn't affect other characters' abilities, and the loss of drop dash doesn't persist between zones. In the decomp, however, selecting Monkey Dude causes the current character's stock icon to be replaced with an "O" (sometimes?), makes some animations loop incorrectly (looking up, ducking, and walking), and sets the ring and score counters to astronomically high numbers. This does affect other characters, and any character affected by this glitch will be turned into a similarly glitchy Sonic after the transition to Green Hill.

I'm not sure if bug compatibility is a goal for this project (especially considering that this seems to be a memory corruption bug), but if it isn't, feel free to close this issue.

**Comment by MGRich** [comment]
I'm not even sure whether or not to tag with incorrect behavior; this is admittedly such a wild bug...

**Comment by Rubberduckycooly** [comment]
pretty sure this is intentional behaviour, as you can see below MonkeyDude's DebugDraw() function uses `self->` vars instead of `DebugMode->animator`, this causes it to overwrite player variables. The difference in behaviour is likely due to the fact this was prolly reported from x64 arch rather than the original's x86 arch.
![image](https://user-images.githubusercontent.com/23735543/187006440-4b73b93d-26bf-45d8-9e0d-aeacea457171.png)

I'll close this issue now, if there's any more concerns or I'm wrong somehow please reopen it and tag me!

**Comment by PatchMixolydic** [comment]
Makes sense! Thanks for looking into this :)
