### ISSUE TITLE
SSZ Crash when Enter metal boss

### ISSUE THREAD

**Issue by Ballsgaming** [Rubberduckycooly/Sonic-Mania-Decompilation#117]
I'm in android and when I'm into the metal sonic boss,the crash but there a chance you can survive the crash

**Comment by LittlePlanetCD** [comment]
What platform are you on, and are you on the latest commits?

**Comment by AhmedUESG** [comment]
> What platform are you on, and are you on the latest commits?

Well to me, i have a huawei Y7 Prime 2019, and the cpu is snapdragon 450, it runs well even on special Stage, Pinball Stage or any other 3d rendered Stage that runs very smooth and no lag, always thanks to ultrawide mania fix as well as the heavy shinobi boss, but when we need to chase metal sonic it crashed, that's because i saw the last log text says: file not found "MornachPlan.gif", and when I cleared the cache it didn't crashed the game and it loaded the mornach plan model
Weird :/

**Comment by stxticOVFL** [comment]
I've yet to see this replicated elsewhere, and the recent filesystem changes should generally fix this.

**Comment by jp438-2** [comment]
I want to add that this issue still exists on Android (POCO X3 NFC). I have compiled it myself on Ubuntu and have Plus enabled.

It has crashed during the loading of the scene with the metal Sonic projector, just after destroying the metal Sonic projector and during the battle with giant metal Sonic. Everything has been perfect up until this point.

@Ballsgaming what device were you using when you experienced the crash, and did you have the Plus DLC enabled?

**Comment by Mefiresu** [comment]
I've been trying to replicate this issue on more easily debuggable platforms (I currently only get it to happen on my Wii port). My guess is that something is broken in the mod loader (engine/RSDKv5 side) but only specifically triggers in this area.

@jp438-2 Would you be able to run the game with the Android Studio debugger attached to get more info about this crash?

**Comment by jp438-2** [comment]
> I've been trying to replicate this issue on more easily debuggable platforms (I currently only get it to happen on my Wii port). My guess is that something is broken in the mod loader (engine/RSDKv5 side) but only specifically triggers in this area.
> 
> @jp438-2 Would you be able to run the game with the Android Studio debugger attached to get more info about this crash?

I just tried this. Running with Android Studio's debugger on my device actually seemed to prevent the mods applying (even though they were all set to active) so I had to use a Bluetooth controller instead of touch. I played up to the giant metal Sonic fight but didn't manage to trigger the crash. Maybe because mods weren't loading and it relates to the mod loader? The mods I use are ultra wide and touch controls and they won't be in common with the Wii version, but if it is the mod loader itself that's probably not relevant. I will experiment again later and see if I can recreate the issue.

**Comment by Mefiresu** [comment]
A complete rebuild is probably needed for debugging (especially if you built the initial version as a release build).

> Maybe because mods weren't loading and it relates to the mod loader? The mods I use are ultra wide and touch controls and they won't be in common with the Wii version, but if it is the mod loader itself that's probably not relevant. 

Correct, the mods themselves are not relevant, something in the mod loader itself may cause this crash (most likely a random memory corruption happening when Metal Sonic first appears).

**Comment by jp438-2** [comment]
I have managed to catch the error twice with Android studio (see screenshots). I don't really know where to go from here though as it seems to just be showing assembly language.

![Screenshot from 2024-05-09 15-37-25](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/assets/1391140/65f6ba88-c8a5-409b-9c57-9cb2c2106cee)
![Screenshot from 2024-05-09 16-00-49](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/assets/1391140/ac6cd745-0acc-4e8a-98c4-0e48d2c37286)

**Comment by Mefiresu** [comment]
I would need the complete stacktrace on the lower left side to better understand where the crash occurs. What's on the screenshot is purely related to the Android SIGSEGV handler and doesn't have any relevant info unfortunately.
Please also throw in the logcat output if you can (should be the cat icon to the left of the stacktrace).
