### ISSUE TITLE
[Android] Game softlocks when transitioning from FBZ1 to FBZ2.

### ISSUE THREAD

**Issue by Shockwave508** [Rubberduckycooly/Sonic-Mania-Decompilation#169]
With the most-current Github builds available, it seems that the game softlocks during the transition from Flying Battery 1 to Flying Battery 2, as all inputs become locked as soon as the transiton ends, can't even bring up the Pause Menu. If it helps any, I had a Magnet Shield active at the time the softlock occured.

![Screenshot_2022-10-21-20-30-21-199_com decomp rsdkv5](https://user-images.githubusercontent.com/32436386/197310670-96c9370f-a9a3-4d48-8e2b-e25a1e33dae3.jpg)

**Comment by Crappy-Productions** [comment]
same here

**Comment by stxticOVFL** [comment]
Android, basegame bug that needs to be fixed in the Ultrawide Mania mod.

**Comment by JuniorTHT** [comment]
Does anyone know if this bug has already been fixed? If so, please post the download link

**Comment by MegAmi24** [comment]
This bug exists in the original game and can be replicated there if you were to extend the screen width. Since the goal of this decomp is to replicate the original game behavior as much as possible, it will not be fixed here. Use the [UltrawideMania mod](https://github.com/RSDKModding/RSDKv5-Example-Mods/tree/master/UltrawideMania) if you want to fix this issue.
