### ISSUE TITLE
How to compile android port on termux?

### ISSUE THREAD

**Issue by cornflakes6374** [Rubberduckycooly/Sonic-Mania-Decompilation#197]
I have the official game files with the plus dlc and i want to compile the android port on termux since my linux laptop is broken. Is there a way to compile the android version on termux? if yes, can you tell me how?

**Comment by Sonic-Geared** [comment]
sadly you can't build the android version in termux, tho you can build the Linux version of it

**Comment by ThisKwasior** [comment]
Managed to do it with Termux + AnLinux (Debian).
Compilation is the same as on desktop, but you need to make sure you run the game in fullscreen when using VNC, otherwise the game crashes because it can't create a video context.

[Here's a video of it running on my phone.](https://cdn.discordapp.com/attachments/801312524850167810/1109488860355895517/SonicManiaTermux.mp4)

**Comment by cornflakes6374** [comment]
Ah okay. Thanks for asking me.
