### ISSUE TITLE
Built the port, wheres the binary? (Not a bug)

### ISSUE THREAD

**Issue by cornflakes6374** [Rubberduckycooly/Sonic-Mania-Decompilation#247]
I finished building the port on linux as my laptop is now fixed and i have my rsdk data, but i can't seem to find the binary. I looked everywhere, but still cant find it. So where is it?

**Comment by LittlePlanetCD** [comment]
What method did you use to build Mania? the makefile or CMake?

**Comment by cornflakes6374** [comment]
Makefile, but i seemed that i forgot to clone the git as recursive part and i might have put the rsdk file in the wrong directory, i will update when the build is done

**Comment by cornflakes6374** [comment]
Now its saying undefined refrence to ogg sync clear. Im on archlinux x86_64

**Comment by cornflakes6374** [comment]
Btw, im building with clang and not gcc.

**Comment by cornflakes6374** [comment]
Here is the log: https://bpa.st/YO46W

**Comment by LittlePlanetCD** [comment]
due to some commits changing stuff, using the normal makefile is not recommended as it can have conflicts.

ensure you're on the latest commits of both Mania and the RSDKv5 dependency that's located in Mania's "dependencies" folder, and use the cmake method:

go into the Sonic-Mania-Decompilation folder, and make a new folder, call it "linuxbuild"
open the terminal in that folder, and if you have cmake installed, run ``cmake ..`` . By default it will generate build files for only mania, but you can specifically do ``cmake .. -DWITH_RSDK=ON`` to output the engine in the same directory as the Mania binary. 

after that, just run ``make`` with your -j count of choice. once done, you can go into the "dependencies/RSDKv5/" folder thats in your "linuxbuild" folder and find the libGame.so and the RSDKv5 binaries you need to run Mania on linux.

**Comment by cornflakes6374** [comment]
> due to some commits changing stuff, using the normal makefile is not recommended as it can have conflicts.
> 
> ensure you're on the latest commits of both Mania and the RSDKv5 dependency that's located in Mania's "dependencies" folder, and use the cmake method:
> 
> go into the Sonic-Mania-Decompilation folder, and make a new folder, call it "linuxbuild" open the terminal in that folder, and if you have cmake installed, run `cmake ..` . By default it will generate build files for only mania, but you can specifically do `cmake .. -DWITH_RSDK=ON` to output the engine in the same directory as the Mania binary.
> 
> after that, just run `make` with your -j count of choice. once done, you can go into the "dependencies/RSDKv5/" folder thats in your "linuxbuild" folder and find the libGame.so and the RSDKv5 binaries you need to run Mania on linux.

It now finally builds and i was able to launch the game with dependencies/RSDKv5/RSDKv5U. Thanks!
